
[server]
listen = "0.0.0.0:6543"

[database]
url = "postgres://postgres:postgres@localhost:5432/postgres"

[limits]
max_rows = 500

[security]
honeytokens = ["_pg_guard_canary"]

[logging]
level = "info"
